export const MIN_USEFUL_LINK_ENERGY = BODYPART_COST[CARRY] * 9 + BODYPART_COST[MOVE]
export const MAX_USEFUL_ENERGY =
    BODYPART_COST[CARRY] * 12 + BODYPART_COST[WORK] * 12 + BODYPART_COST[MOVE] * 24
export const MAX_DROPPED_RESOURCES = 1000
export const LATENT_WORKER_INTERVAL_MULTIPLIER = 200
export const SPAWN_CHECK_MOD = 4
export const UPGRADERS_COUNT = 1
export const BUILDERS_COUNT = 1
export const MASON_COUNT = 1
export const RESCUE_WORKER_COUNT = 3
export const ATTACKERS_COUNT = 2
